ARG NODE_VERSION=8
FROM "node:${NODE_VERSION}-alpine"
ARG CLI_VERSION=latest
ARG NG_NEW_ARGS=
ARG NG_NEW_NAME=test-scuri-app
RUN npm init -y
RUN npm i @angular/cli@$CLI_VERSION
RUN npx -p @angular/cli@$CLI_VERSION ng new --interactive=false --defaults --skip-git --routing $NG_NEW_ARGS $NG_NEW_NAME
WORKDIR $NG_NEW_NAME
COPY . ./src
COPY ./run.sh .
EXPOSE 4200
ENTRYPOINT ./run.sh
