name: Push scuri test dockerfiles
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
       -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: gparlakov/scuri:angular-14-app-v2
          file: ./scuri-test-context/Dockerfile_with_chrome_headless
          context: ./scuri-test-context
          build-args: 
            CLI_VERSION=14
            NG_NEW_NAME=test-scuri-ng14-app 
            NODE_VERSION=14
