name: Push scuri test dockerfiles

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ng-app-14
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: gparlakov/scuri:angular-14-app-v2
          file: ./scuri-test-context/Dockerfile_with_chrome_headless
          context: ./scuri-test-context
          build-args: |
            CLI_VERSION=14
            NG_NEW_NAME=test-scuri-ng14-app 
            NODE_VERSION=14
      -
        name: Build and push ng-app-13
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: gparlakov/scuri:angular-13-app-v1
          file: ./scuri-test-context/Dockerfile_with_chrome_headless
          context: ./scuri-test-context
          build-args: |
            CLI_VERSION=13
            NG_NEW_NAME=test-scuri-ng13-app 
            NODE_VERSION=13
